"""Pre-registration for V10. Hash-locked, written from SPEC_V10 before any V10 code ran.

This card carries something the previous nine do not: the AUTHOR'S STATED RESPONSE to each outcome,
recorded before the runs. A prediction alone lets a null be reframed afterwards as uninteresting. A
prediction plus a stated consequence cannot be.
"""
from __future__ import annotations

import hashlib
import json

from .v10 import PREREG_PATH, v10_dir

CARD = {
    "version": "v10",
    "title": "The reader as a defence, and what rides in anyway",
    "written_before_code": True,
    "hypotheses": {
        "H10.1": ("On empty grooming, the intent-gate absorbs less than the surface filter at "
                  "equal or better retention of genuine work."),
        "H10.2": ("On mimicry, the intent-gate does NO BETTER and may do WORSE than the surface "
                  "filter. Predicted against interest."),
        "H10.3": ("The learned-values reader shows monotone value drift and its gate widens as it "
                  "drifts -- the doom loop."),
        "H10.4": ("The rider drifts comparably to the ungated reader despite a shut value gate. "
                  "Values ride in on process."),
        "H10.5": ("Adversarial engagement suppresses goal and value uptake substantially more than "
                  "process uptake."),
        "H10.6": ("Process uptake predicts value uptake at fixed goal uptake. Bar: partial "
                  "correlation above 0.2."),
        "H10.7": ("With evasion tracking detection, the false-alarm rate is NON-MONOTONE in "
                  "detector training."),
        "H10.8": "A stale detector fails ASYMMETRICALLY rather than simply becoming noisy.",
    },
    "nulls": {
        "N45": "on a clean corpus the intent-gate costs nothing",
        "N46": "the surface filter works on something",
        "N47": "the intent-gate never reads the provenance signal",
        "N48": "the E56 design varies process uptake while holding goal readability fixed",
        "N49": "with evasion off, E57 reproduces E53's monotone decline",
        "N50": "value drift is zero on a clean corpus, for every reader",
        "N51": "reader 7's value gate is verifiably shut",
    },
    "authors_recorded_priors": {
        "H10.6": ("the author predicts values ride in on process, citing mere exposure, and stated "
                  "before the run that a null would be read as evidence the MODEL is wrong rather "
                  "than as an uninteresting negative"),
        "N45": ("the author flagged this as the null he most expected to fail, named E8 as the "
                "reason, and directed the run to proceed on the stated grounds that the project's "
                "present position is one of overconfidence and the correct response to "
                "overconfidence is more validation rather than less"),
    },
    "may_not_claim": ("the contamination motivating E55 is documented; no causal attribution of "
                      "real-world model value-drift to any real-world actor is made or supported"),
    "severity_rule": ("every V10 headline gets a severity draw and an ablation row before it gets "
                      "a sentence in any document, because V9 established that every finding in "
                      "this project rests on one commitment -- the reader modelling a maker -- so "
                      "any new finding generated by looking at this model will also reproduce"),
    "not_built": [
        "the human acquisition test -- top external priority on the human side",
        "the terminal AI-side step: an intent-gate in a real training pipeline on real corpora",
        "distributed authorship, tool delegation, recursion",
    ],
}


def write_card() -> dict:
    v10_dir()
    body = json.dumps(CARD, sort_keys=True, separators=(",", ":")).encode("utf-8")
    payload = dict(CARD)
    payload["sha256"] = hashlib.sha256(body).hexdigest()
    PREREG_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return payload


def verify() -> bool:
    if not PREREG_PATH.exists():
        return False
    stored = json.loads(PREREG_PATH.read_text(encoding="utf-8"))
    digest = stored.pop("sha256", None)
    body = json.dumps(stored, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return bool(digest == hashlib.sha256(body).hexdigest())


if __name__ == "__main__":
    print(write_card()["sha256"])
