"""X08 executed pure-noise feedback with misleading experienced progress.

Fixed known-answer sequences are selected from the declared iid physical world.
They are adversarial witnesses, never a random-sample success rate.
"""
from itertools import product
import math
import random
from .inquiry_world import outcome
from .inquiry_stable_reference import PRIOR, learned, chosen, constructed
from .reference import interpret
from .recoding import close

PREFIX = "ghostscale.validation.soundingline.v16.inquiry_stable:"


def noise_case(log, direction="decline"):
    if direction not in {"decline", "rise"}:
        raise ValueError("unknown fixed progress witness")
    # Each physical outcome is generated by the actual noise ecology. Selecting
    # a witness with this pattern is disclosed; it is not an estimate of frequency.
    pattern = [1, 2]+([0, 0, 1, 1] if direction == "decline" else [1, 1, 0, 0])
    chosen_seed = None
    for seed in range(100000):
        rng = random.Random(seed)
        if [rng.randrange(4) for _ in range(6)] == pattern:
            chosen_seed = seed
            break
    if chosen_seed is None:
        raise ValueError("finite known-noise witness unavailable")
    rng = random.Random(chosen_seed)
    world = {"mappings": [[0, 1, 2, 3], [0, 1, 2, 3]]}
    physical = [outcome(world, 0, 0, noisy=True, rng=rng) for _ in pattern]
    physical_ok = all(item["artifact"] == interpret(item["program"])["artifact"]
                      and item["primitive_cost"] == 1 and item["legal"] for item in physical)
    examples = [{"domain": 0, "command": row["command"], "cell": row["cell"]} for row in physical]
    # The comparison domain is actually learned to saturation, not given its map.
    stable = [outcome(world, 1, command, noisy=False, rng=random.Random(0)) for command in range(4)]
    examples += [{"domain": 1, "command": row["command"], "cell": row["cell"]} for row in stable]
    learning = {"beliefs": [list(PRIOR), list(PRIOR)], "examples": examples, "forget_domains": []}
    result = log.call(PREFIX+"learn_public", learning)
    history = [{"success": row["cell"] == 0, "surprise": math.log(4), "command": 0,
                "cell": row["cell"]} for row in physical[-4:]]
    payload = {"schema_version": "v16.inquiry.1", "task_id": "noise-known-control",
        "beliefs": result["beliefs"], "offers": [0, 0], "histories": [history, [{"success": True, "surprise": 0.0}]*4],
        "familiarity": [4, 4], "pending_commands": [[], []], "feedback_batches": [1, 1],
        "future_weights": [0.5, 0.5], "opportunity_cost": 0.01, "remaining_interactions": 2,
        "tie_draw": 0.9, "committed_domain": None, "offer_probabilities": [[0.25]*4, [0.25]*4]}
    policies = {name: log.call(PREFIX+"choose", payload, policy=name)
                for name in ["absolute-progress", "signed-progress", "surprise", "value-learning"]}
    construction = log.call(PREFIX+"construct_public", {"beliefs": result["beliefs"]})
    # Independently execute every pair of physical noise outcomes. All policies'
    # command choices have the same two-of-sixteen success probability.
    future = []
    for item in construction["programs"]:
        if item["domain"] != 0:
            continue
        outcomes = [interpret([a, b])["artifact"] == item["goal"] for a, b in product(range(4), repeat=2)]
        future.append({"goal": item["goal"], "program": item["commands"],
                       "successes": sum(outcomes), "possibilities": len(outcomes)})
    checks = {"actual_noise_feedback_executed": physical_ok and [item["cell"] for item in physical] == pattern,
        "noise_inferred_from_conflicting_returned_observations": result["beliefs"][0][-1] == 1,
        "learning_matches_independent_scalar_reference": close(result, learned(learning)),
        "actual_policies_match_independent_scalar_reference": all(close(value, chosen(payload, name)) for name, value in policies.items()),
        "construction_matches_independent_scalar_reference": close(construction, constructed({"beliefs": result["beliefs"]})),
        "absolute_progress_chases_unlearnable_noise": policies["absolute-progress"]["domain"] == 0,
        "surprise_chases_unlearnable_noise": policies["surprise"]["domain"] == 0,
        "value_learning_declines_zero_gain": policies["value-learning"]["domain"] is None,
        "query_has_negative_net_expected_value": all(abs(score+0.01) < 1e-12 for score in policies["value-learning"]["scores"]),
        "future_noise_competence_remains_one_eighth": len(future) == 6 and all(row["successes"] == 2 and row["possibilities"] == 16 for row in future),
        "signed_policy_distinguishes_decline_from_rise": policies["signed-progress"]["domain"] == (1 if direction == "decline" else 0)}
    return checks, {"known_witness_seed": chosen_seed, "selection": "first seeded iid physical sequence with declared pattern; no frequency claim",
        "pattern": pattern, "physical_feedback": physical, "stable_feedback": stable,
        "future_noise_enumeration": future, "primitive_cost": len(physical)+len(stable)+6*16*2,
        "independent_future_enumeration_is_fixture_work": True, "direction": direction}
