"""Assemble the V14 results packet from the verdicts, ledgers and locks (spec §21).

The packet is final: it is written only after the window's deadline, from the committed
record, once. There is no interim packet under the one-window contract; ``--draft`` writes a
draft to a path outside docs/ for a dry run of the generator and never to the packet's home.

    ./.venv/Scripts/python.exe runners/report_v14.py
    ./.venv/Scripts/python.exe runners/report_v14.py --draft results/v14/smoke/RESULTS_PACKET_DRAFT.md
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import ghostscale.validation.soundingline.v14 as V                          # noqa: E402
from ghostscale.validation.soundingline.v14 import common as C              # noqa: E402
from ghostscale.validation.soundingline.v14 import manifest as M            # noqa: E402

OUT = REPO / "docs" / "versions" / "v14-routed-reader" / "RESULTS_PACKET.md"
TRUNKS = "IJREAHFBX"


def crit_of(v):
    return [bool(x["passed"]) for k, x in (v or {}).get("results", {}).items() if k.startswith("criterion_") and isinstance(x, dict) and "passed" in x]


def gates_of(v):
    g = (v or {}).get("gates", {})
    glist = g.get("gates", [])
    failed = g.get("failed_names", [])
    s = f"{len(glist) - len(failed)}/{len(glist)}"
    return s + (f" failed: {', '.join(failed[:4])}" if failed else "")


def lane_of(d: dict) -> str:
    if d["trunk"] == "X":
        return "attack"
    return "discovery" if "discovery" in d.get("lanes", ["discovery"]) else "transfer"


def window_lines() -> list:
    lines = ["## The window", ""]
    if M.DEADLINE.exists():
        w = json.loads(M.DEADLINE.read_text(encoding="utf-8"))
        lines.append(f"Opened {w['opened']}; deadline {w['deadline']} ({w['window_hours']:.0f} h, freeze at hour {w['freeze_hour']:.0f}); immutable across restarts.")
        closed = w.get("window_closed_cards", [])
        lines.append(f"Cards not opened because the window had closed: {', '.join(c['card'] for c in closed) if closed else 'none'}.")
    else:
        lines.append("No window record.")
    sr = V.V14_RESULTS / "SHORT_RUN.json"
    if sr.exists():
        s = json.loads(sr.read_text(encoding="utf-8"))
        lines.append(f"SHORT_RUN: {'yes' if s.get('short_run') else 'no'} — last unit finished at hour {s.get('last_unit_hour', float('nan')):.2f}." + (f" {s['note']}" if s.get("note") else ""))
    co = V.V14_RESULTS / "COEXISTENCE.json"
    if co.exists():
        c = json.loads(co.read_text(encoding="utf-8"))
        dec = c.get("decisions", [])
        lines.append(f"Coexistence: {len(c.get('samples', []))} samples of the sibling's scheduler status; governor decisions: "
                     + ("; ".join(f"{d['action']} {d['from']}→{d['to']} at {d['at']}" for d in dec) if dec else "none") + ".")
    lines.append("")
    return lines


def main(out_path: Path | None = None, draft: bool = False) -> None:
    from ghostscale.prereg_v14 import ATTACK_RELEVANCE, FLIGHTS, FLIGHT_CARDS, FLIGHT_PRIMARY_CARD
    if not draft:
        if not M.DEADLINE.exists():
            sys.exit("report refused: no window was opened")
        w = json.loads(M.DEADLINE.read_text(encoding="utf-8"))
        if time.time() < w["deadline_epoch"]:
            sys.exit(f"report refused: the deadline ({w['deadline']}) has not passed; there is no interim packet")
    doc = M.load_manifest()
    cov = M.coverage(doc)
    by_id = {d["id"]: d for d in doc["cards"]}
    lines = ["# V14 — The Routed Reader. Results packet (generated by runners/report_v14.py)", "",
             f"Generated {time.strftime('%Y-%m-%d %H:%M')}{' — DRAFT, not the final packet' if draft else ' after the deadline'}. "
             f"Coverage: {cov['mandatory_resolved']}/{cov['mandatory_total']} mandatory cards resolved; states {cov['by_state']}. "
             f"Tier: {doc.get('selected_tier')}. This is the analyst appendix (Pass B); the read-first account (Pass A) is RESULTS.md beside it.", ""]
    lines += window_lines()
    lines += ["## Flights", "", "The five constructed-world results the program was allowed to claim, with the state of every card each rests on, "
              "the attacks that applied and whether the effect survived them, and confirmation. A flight stands only if its primary card landed "
              "with its criterion held, the relevant attacks were survived, and confirmation held.", ""]
    conf = V.V14_RESULTS / "CONFIRMATION.json"
    led = json.loads(conf.read_text(encoding="utf-8")) if conf.exists() else {"cards": {}, "frozen": None}
    for fl in FLIGHTS:
        rows = []
        for cid in FLIGHT_CARDS.get(fl, []):
            d = by_id.get(cid)
            v = C.load_verdict(cid, lane_of(d)) if d else None
            cr = crit_of(v)
            crow = led["cards"].get(cid, {})
            rows.append(f"{cid}{' (primary)' if FLIGHT_PRIMARY_CARD.get(fl) == cid else ''}: {v.get('state') if v else 'unrun'}"
                        + ("/criteria held" if cr and all(cr) else ("/criteria failed" if cr else ""))
                        + (f", confirmation {'held' if crow.get('criteria_passed_confirmation') else 'failed'}" if "criteria_passed_confirmation" in crow else ""))
        attacks = []
        for xid, flights in ATTACK_RELEVANCE.items():
            if fl not in flights:
                continue
            xv = C.load_verdict(xid, "attack")
            res = (xv or {}).get("results", {})
            surv = None
            for k, x in res.items():
                if isinstance(x, dict) and fl in x:
                    surv = x[fl]
                    break
                if k.startswith("criterion_") and isinstance(x, dict) and isinstance(x.get("survival"), dict) and fl in x["survival"]:
                    surv = x["survival"][fl]
                    break
            attacks.append(f"{xid}: {surv if surv is not None else ((xv or {}).get('state') or 'unrun')}")
        lines.append(f"- **{fl}** — " + "; ".join(rows) + (f". Attacks — {'; '.join(attacks)}" if attacks else ""))
    lines.append("")
    lines += ["## Cards", "", "Columns: card; lane; state; registered ceiling; criterion; gates passed over run (failed names); "
              "the card's own one-sentence account of what happened.", ""]
    for trunk in TRUNKS:
        cards = [c for c in doc["cards"] if c["trunk"] == trunk]
        if not cards:
            continue
        lines += [f"### Trunk {trunk}", "", "| card | lane | state | ceiling | criterion | gates | what happened |", "|---|---|---|---|---|---|---|"]
        for c in cards:
            lane = lane_of(c)
            v = C.load_verdict(c["id"], lane)
            if v is None:
                lines.append(f"| {c['id']} | {lane} | {c['status']} | | | | not run |")
                continue
            cr = crit_of(v)
            crs = ("held" if all(cr) else "failed") if cr else "recorded"
            wh = v.get("record", {}).get("what_happened", "").replace("|", "/")[:400]
            closure = f" ({v.get('closure_reason', '')[:80]})" if v.get("closure_reason") else ""
            lines.append(f"| {c['id']} | {lane} | {v.get('state')}{closure} | {v.get('claim_ceiling')} | {crs} | {gates_of(v)} | {wh} |")
        lines.append("")
    tv = [c for c in doc["cards"] if "transfer" in c.get("lanes", []) and "discovery" in c.get("lanes", []) and C.load_verdict(c["id"], "transfer")]
    if tv:
        lines += ["## Transfer lane (cards also run in discovery)", "", "| card | state | criterion | gates |", "|---|---|---|---|"]
        for c in tv:
            v = C.load_verdict(c["id"], "transfer")
            cr = crit_of(v)
            lines.append(f"| {c['id']} | {v.get('state')} | {('held' if all(cr) else 'failed') if cr else 'recorded'} | {gates_of(v)} |")
        lines.append("")
    if led.get("frozen"):
        fz = led["frozen"]
        held = [k for k, x in led["cards"].items() if x.get("criteria_passed_confirmation") is True]
        failed = [k for k, x in led["cards"].items() if x.get("criteria_passed_confirmation") is False]
        lines += ["## Confirmation", "", f"Frozen at hour {fz.get('frozen_at_hour', 'n/a')} under the rule '{(fz.get('selection') or {}).get('rule', '')}': {', '.join(fz.get('promoted', []))} "
                  f"(eligible: {', '.join((fz.get('selection') or {}).get('eligible', [])) or 'none'}).",
                  f"Held on the untouched lineage: {', '.join(held) or 'none'}. Failed: {', '.join(failed) or 'none'}. "
                  f"Not opened: {', '.join(k for k, x in led['cards'].items() if x.get('state') == 'WINDOW_CLOSED') or 'none'}.", ""]
    else:
        lines += ["## Confirmation", "", "No packet was frozen.", ""]
    if M.RUNTIME.exists():
        rt = json.loads(M.RUNTIME.read_text(encoding="utf-8"))
        cards = rt.get("cards", {})
        wall = sum(x.get("wall_s", 0) or 0 for x in cards.values())
        cpu = sum(x.get("children_cpu_s", 0) or 0 for x in cards.values())
        wl = V.V14_RESULTS / "WORKLOAD_LOCK.json"
        fc = json.loads(wl.read_text(encoding="utf-8")).get("forecast", {}) if wl.exists() else {}
        lines += ["## Runtime", "", f"Total wall across card runs {wall / 3600:.1f} h; summed child CPU {cpu / 3600:.1f} h across {len(cards)} card runs. "
                  f"Forecast at lock: {fc.get('hours', float('nan')):.1f} h under rule '{fc.get('rule')}'.", ""]
    lines += ["## Locks and ledgers", ""]
    for name in ("prereg_v14_structural_lock.json", "WORKLOAD_LOCK.json", "prereg_v14_lock.json", "COMPLETION.json", "PILOT.json", "FORECAST.json",
                 "DEADLINE.json", "SHORT_RUN.json", "COEXISTENCE.json", "CLAIM_LEDGER.json", "ROUTE_INFORMATION.json", "ATTACK_MATRIX.json"):
        p = V.V14_RESULTS / name
        lines.append(f"- `results/v14/{name}`: {'present' if p.exists() else 'absent'}" + (f", sha256 {C.file_sha(p)[:16]}" if p.exists() else ""))
    lines += ["", "Nothing in this packet describes a person; every result is a property of a constructed world and its stated reader."]
    target = out_path or OUT
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("wrote", target)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--draft", default=None, help="write a draft to this path (outside docs/); never the packet")
    a = ap.parse_args()
    if a.draft:
        p = Path(a.draft)
        if "docs" in p.resolve().parts:
            sys.exit("a draft may not be written under docs/")
        main(p, draft=True)
    else:
        main()
