"""Assemble the V13 results packet from the verdicts, ledgers and locks (spec §21).

Pass A (read first) is plain language and is generated from each verdict's own plain-language
record; Pass B is the analyst appendix. Every number is read from a committed file. Run at any
time; the packet reflects whatever has landed so far.

    ./.venv/Scripts/python.exe runners/report_v13.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

import ghostscale.validation.soundingline.v13 as V                          # noqa: E402
from ghostscale.validation.soundingline.v13 import common as C              # noqa: E402
from ghostscale.validation.soundingline.v13 import manifest as M            # noqa: E402

OUT = REPO / "docs" / "versions" / "v13-common-ground" / "RESULTS_PACKET.md"
FLIGHT_CARDS = {"nested_common_ground": ["C04", "C05", "C14", "C16"], "cost_aware_maker_inference": ["O02", "O06", "O07", "O17"],
                "attention_as_safe_allocation": ["A02", "A03", "A10", "A12", "A13", "A14"],
                "factored_epistemic_vigilance": ["G01", "G04", "G05", "G13", "G15", "G16"],
                "readable_interaction_hand": ["H03", "H07", "H12", "H13", "H15", "H16"]}


def crit_of(v):
    out = []
    for k, x in (v or {}).get("results", {}).items():
        if k.startswith("criterion_") and isinstance(x, dict) and "passed" in x:
            out.append(bool(x["passed"]))
    return out


def gates_of(v):
    g = (v or {}).get("gates", {})
    glist = g.get("gates", [])
    failed = g.get("failed_names", [])
    return f"{len(glist) - len(failed)}/{len(glist)}" + (f" failed: {', '.join(failed[:4])}" for _ in [0]).__next__() if failed else f"{len(glist)}/{len(glist)}"


def main() -> None:
    doc = M.load_manifest()
    cov = M.coverage(doc)
    lines = ["# V13 — Common Ground. Results packet (generated by runners/report_v13.py)", "",
             f"Generated {time.strftime('%Y-%m-%d %H:%M')}. Coverage: {cov['mandatory_resolved']}/{cov['mandatory_total']} mandatory cards resolved; "
             f"states {cov['by_state']}. Tier: {doc.get('selected_tier')}. This packet is the analyst appendix (Pass B); the read-first "
             f"account (Pass A) is RESULTS.md beside it.", "",
             "## Flights", "", "The five constructed-world results the program was allowed to claim, with the state of every card each rests on. "
             "A flight stands only if its cards landed, their criteria held, the relevant attacks were survived, and confirmation held.", ""]
    for fl, cards in FLIGHT_CARDS.items():
        rows = []
        for cid in cards:
            v = C.load_verdict(cid, "discovery")
            cr = crit_of(v)
            conf = C.load_verdict(cid, "confirmation")
            ccr = crit_of(conf)
            rows.append(f"{cid}: {v.get('state') if v else 'unrun'}{'/criteria held' if cr and all(cr) else ('/criteria failed' if cr else '')}"
                        + (f", confirmation {'held' if ccr and all(ccr) else 'failed'}" if ccr else ""))
        lines.append(f"- **{fl}** — " + "; ".join(rows))
    lines.append("")
    lines += ["## Cards", "", "Columns: card; state (discovery); registered ceiling; criterion; gates passed over run (failed names); "
              "the card's own one-sentence account of what happened.", ""]
    for trunk in "ICAOPGHQLX":
        cards = [c for c in doc["cards"] if c["trunk"] == trunk]
        if not cards:
            continue
        lines += [f"### Trunk {trunk}", "", "| card | state | ceiling | criterion | gates | what happened |", "|---|---|---|---|---|---|"]
        for c in cards:
            lane = "attack" if trunk == "X" else "discovery"
            v = C.load_verdict(c["id"], lane)
            if v is None:
                lines.append(f"| {c['id']} | {c['status']} | | | | not run |")
                continue
            cr = crit_of(v)
            crs = ("held" if all(cr) else "failed") if cr else "recorded"
            wh = v.get("record", {}).get("what_happened", "").replace("|", "/")[:400]
            closure = f" ({v.get('closure_reason', '')[:80]})" if v.get("closure_reason") else ""
            lines.append(f"| {c['id']} | {v.get('state')}{closure} | {v.get('claim_ceiling')} | {crs} | {gates_of(v)} | {wh} |")
        lines.append("")
    # transfer and confirmation
    conf = V.V13_RESULTS / "CONFIRMATION.json"
    if conf.exists():
        led = json.loads(conf.read_text(encoding="utf-8"))
        held = [k for k, x in led.get("cards", {}).items() if x.get("criteria_passed_confirmation") is True]
        failed = [k for k, x in led.get("cards", {}).items() if x.get("criteria_passed_confirmation") is False]
        lines += ["## Confirmation", "", f"Promoted (frozen): {', '.join((led.get('frozen') or {}).get('promoted', []))}.",
                  f"Held on the untouched lineage: {', '.join(held) or 'none yet'}. Failed: {', '.join(failed) or 'none'}.", ""]
    # runtime audit
    if M.RUNTIME.exists():
        rt = json.loads(M.RUNTIME.read_text(encoding="utf-8"))
        cards = rt.get("cards", {})
        wall = sum(x.get("wall_s", 0) or 0 for x in cards.values())
        cpu = sum(x.get("children_cpu_s", 0) or 0 for x in cards.values())
        wl = V.V13_RESULTS / "WORKLOAD_LOCK.json"
        fc = json.loads(wl.read_text(encoding="utf-8")).get("forecast", {}) if wl.exists() else {}
        lines += ["## Runtime", "", f"Total wall across card runs {wall / 3600:.1f} h; summed child CPU {cpu / 3600:.1f} h across {len(cards)} card runs. "
                  f"Forecast at lock: {fc.get('hours', float('nan')):.1f} h under rule '{fc.get('rule')}'.", ""]
    lines += ["## Locks and ledgers", ""]
    for name in ("prereg_v13_structural_lock.json", "WORKLOAD_LOCK.json", "prereg_v13_lock.json", "COMPLETION.json", "PILOT.json", "FORECAST.json"):
        p = V.V13_RESULTS / name
        lines.append(f"- `results/v13/{name}`: {'present' if p.exists() else 'absent'}" + (f", sha256 {C.file_sha(p)[:16]}" if p.exists() else ""))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
