"""Assemble the V12 results packet from the verdicts and the manifest (spec section 22).

The packet is generated, not written: every number in it is read from a verdict file, so the
narrative documents can quote it without re-deriving anything. Run after any card lands:

    ./.venv/Scripts/python.exe runners/report_v12.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from ghostscale.validation.soundingline.v12 import manifest as M, verdict_dir   # noqa: E402

SKIP = {"per_world", "cells", "rows", "by_world", "cell_matrix", "ledgers", "n_rows", "note", "detail",
        "attack", "gain_surface", "reproduction_surface", "morris", "sobol", "off_ceiling", "linear_effects"}


def scalar_summary(res: dict, max_items: int = 12) -> list:
    """Flatten numeric leaves and bootstrap means into short 'key: value' strings."""
    out = []

    def walk(prefix, obj, depth):
        if len(out) >= max_items:
            return
        if isinstance(obj, dict):
            if "mean" in obj and isinstance(obj["mean"], (int, float)):
                iv = obj.get("interval")
                s = f"{prefix}: {obj['mean']:.3f}"
                if iv and iv[0] is not None and iv[0] == iv[0]:
                    s += f" [{iv[0]:.3f}, {iv[1]:.3f}]"
                out.append(s)
                return
            for k, v in obj.items():
                if k in SKIP or len(out) >= max_items:
                    continue
                if depth < 3:
                    walk(f"{prefix}.{k}" if prefix else k, v, depth + 1)
        elif isinstance(obj, bool):
            out.append(f"{prefix}: {obj}")
        elif isinstance(obj, (int, float)):
            out.append(f"{prefix}: {obj:.3f}" if isinstance(obj, float) else f"{prefix}: {obj}")
    walk("", res, 0)
    return out


def main() -> None:
    doc = M.load_manifest()
    cov = M.coverage(doc)
    lines = ["# V12 — The Other Model. Results packet (generated by runners/report_v12.py)", "",
             f"Coverage: {cov['mandatory_resolved']}/{cov['mandatory_total']} mandatory cards resolved. "
             f"States: {cov['by_state']}.", "",
             "Columns: card id; manifest state; the claim ceiling the card was registered under; the "
             "pre-specified criterion where the card has one (recorded = the card reports, it does not "
             "pass or fail); gates passed over gates run, with the names of any that failed; and the "
             "headline numbers read from the verdict (bootstrap intervals in brackets).", ""]
    for trunk in "ISQBURTDFX":
        cards = [c for c in doc["cards"] if c["trunk"] == trunk]
        lines += [f"## Trunk {trunk}", "", "| card | state | ceiling | criterion | gates | headline numbers |", "|---|---|---|---|---|---|"]
        for c in cards:
            p = verdict_dir() / f"{c['id']}.json"
            if not p.exists():
                lines.append(f"| {c['id']} | {c['status']} | | | | not run |")
                continue
            v = json.loads(p.read_text(encoding="utf-8"))
            gates = v.get("gates", {})
            glist = gates.get("gates", []) if isinstance(gates, dict) else (gates or [])
            failed = [g["name"] for g in glist if isinstance(g, dict) and not g.get("passed", True) and not g.get("expected_to_fail")]
            crit = []
            for k, x in v.get("results", {}).items():
                if k.startswith("criterion_"):
                    if isinstance(x, dict) and "passed" in x:
                        crit.append(f"{k.replace('criterion_C_', '')}: {'passed' if x['passed'] else 'not passed'}")
                    else:
                        crit.append(k)
            gate_s = f"{len(glist) - len(failed)}/{len(glist)}" + (f" failed: {', '.join(failed)}" if failed else "")
            nums = "<br>".join(scalar_summary(v.get("results", {})))
            closure = f" ({v.get('closure_reason')})" if v.get("closure_reason") else ""
            lines.append(f"| {c['id']} | {v.get('state')}{closure} | {v.get('claim_ceiling')} | {'; '.join(crit) or 'recorded'} | {gate_s} | {nums} |")
        lines.append("")
    lines += ["## Runtime", ""]
    rt = M.RUNTIME
    if rt.exists():
        r = json.loads(rt.read_text(encoding="utf-8"))
        total = sum(x.get("wall_seconds", 0) for x in r.get("cards", {}).values())
        lines.append(f"Workers {r.get('workers')}, priority {r.get('priority')}, total wall {total / 60:.1f} min across {len(r.get('cards', {}))} cards.")
    out = REPO / "docs/versions/v12-the-other-model/RESULTS_PACKET.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
